<?php
require_once 'Src/autoload.php';
//add gps = 'on' ;
//add addDriver = 'on';
$base = new Src\Rates\BasicCarRent();
$hourly = new Src\Rates\HourlyCarRent();
$daily = new Src\Rates\DailyCarRent();
$student = new Src\Rates\StudentCarRent();
echo "<h2>Тариф базовый</h2>";
$base->getDataForCalculation(5, 2, 20, 'on');
$base->getDataForCalculation(3, 6, 24);
$base->getDataForCalculation('no', 2, 'no');
$base->getDataForCalculation(5, 2, 17);
echo "<h2>Тариф почасовой</h2>";
$hourly->getDataForCalculation(5, 2, 20, 'on', 'on');
$hourly->getDataForCalculation(3, 6, 24);
$hourly->getDataForCalculation('no', 2, 'no');
$hourly->getDataForCalculation(5, 0.55, 66);
echo "<h2>Тариф суточный</h2>";
$daily->getDataForCalculation(5, 2, 20, 'on', 'on');
$daily->getDataForCalculation(24.30, 6, 24, 'on');
$daily->getDataForCalculation(10, 24.31, 18, 'off', 'on');
$daily->getDataForCalculation(5, 24.30, 25);
echo "<h2>Тариф студенческий</h2>";
$student->getDataForCalculation(5, 2, 20, 'on');
$student->getDataForCalculation(3, 6, 26);
$student->getDataForCalculation('no', 2, 17);
$student->getDataForCalculation(5, 2, 25, 'on');
$student->getDataForCalculation(5, 2, 'no');
